// 马可福音 4 · 和合本简体中文（CUV）
// Scripture text is grouped into natural reading scenes; punctuation stays non-clickable.
import mark32035 from './mark-3-20-35.js';

const mark4Entries = [
  ['教训', 'jiàoxun', 'to teach; teaching'], ['到', 'dào', 'to arrive at; to'],
  ['只得', 'zhǐdé', 'have no choice but to'], ['上船', 'shàng chuán', 'to board a boat'],
  ['坐下', 'zuòxia', 'to sit down'], ['船', 'chuán', 'boat'], ['海里', 'hǎilǐ', 'in the sea'],
  ['靠近', 'kàojìn', 'to come close to'], ['海', 'hǎi', 'sea'], ['站在', 'zhàn zài', 'to stand at'],
  ['岸上', 'ànshàng', 'on the shore'], ['道理', 'dàoli', 'teaching; truth'],
  ['之间', 'zhījiān', 'between; among'], ['听', 'tīng', 'to listen; hear'], ['啊', 'a', 'an exclamation'],
  ['撒种', 'sā zhǒng', 'to sow seed'], ['撒', 'sā', 'to scatter; sow'], ['时候', 'shíhou', 'time; when'],
  ['落在', 'luò zài', 'to fall on'], ['路旁', 'lùpáng', 'beside the path'], ['飞鸟', 'fēiniǎo', 'birds'],
  ['吃尽', 'chī jìn', 'to eat it all'], ['土浅', 'tǔ qiǎn', 'shallow soil'],
  ['石头地', 'shítou dì', 'rocky ground'], ['土', 'tǔ', 'soil; earth'], ['既', 'jì', 'since; already'],
  ['深', 'shēn', 'deep'], ['发苗', 'fā miáo', 'to sprout'], ['最快', 'zuì kuài', 'fastest'],
  ['日头', 'rìtou', 'sun'], ['一晒', 'yí shài', 'when the sun shines on it'],
  ['没有', 'méiyǒu', 'not have; there is no'], ['根', 'gēn', 'root'], ['荆棘', 'jīngjí', 'thorns'],
  ['里', 'lǐ', 'inside'], ['长起来', 'zhǎng qǐlái', 'to grow up'], ['它', 'tā', 'it'],
  ['挤住', 'jǐ zhù', 'to crowd out; choke'], ['结实', 'jiē shí', 'to bear fruit'],
  ['好土', 'hǎo tǔ', 'good soil'], ['发生', 'fāshēng', 'to grow; develop'], ['长大', 'zhǎng dà', 'to grow big'],
  ['三十倍', 'sānshí bèi', 'thirty times'], ['六十倍', 'liùshí bèi', 'sixty times'],
  ['一百倍', 'yìbǎi bèi', 'one hundred times'], ['耳', 'ěr', 'ear'], ['可听', 'kě tīng', 'able to hear'],
  ['应当', 'yīngdāng', 'should; ought to'], ['无人', 'wú rén', 'no one; when no one else is present'],
  ['神国', 'Shén guó', 'the kingdom of God'], ['奥秘', 'àomì', 'mystery; secret truth'],
  ['只', 'zhǐ', 'only'], ['知道', 'zhīdào', 'to know'], ['若是', 'ruòshì', 'if; if it is'],
  ['外人', 'wàirén', 'outsiders'], ['讲', 'jiǎng', 'to speak; explain'], ['凡事', 'fánshì', 'everything'],
  ['晓得', 'xiǎode', 'to understand; know'], ['明白', 'míngbai', 'to understand clearly'],
  ['恐怕', 'kǒngpà', 'lest; for fear that'], ['回转', 'huízhuǎn', 'to turn back'],
  ['过来', 'guòlai', 'back; over'], ['得', 'dé', 'to receive; obtain'], ['吗', 'ma', 'question particle'],
  ['这样', 'zhèyàng', 'like this; in this way'], ['撒种之人', 'sā zhǒng zhī rén', 'the sower'],
  ['道', 'dào', 'the word; message'], ['撒在', 'sā zài', 'to sow on'], ['立刻', 'lìkè', 'immediately'],
  ['心里', 'xīnlǐ', 'in the heart'], ['夺了去', 'duó le qù', 'to take away'],
  ['欢喜', 'huānxǐ', 'glad; joyful'], ['领受', 'lǐngshòu', 'to receive; accept'],
  ['但', 'dàn', 'but'], ['不过', 'búguò', 'only; merely'], ['暂时', 'zànshí', 'temporary; for a time'],
  ['及至', 'jízhì', 'when; by the time'], ['为', 'wèi', 'because of; for'], ['遭了', 'zāo le', 'to experience; suffer'],
  ['患难', 'huànnàn', 'trouble; suffering'], ['或是', 'huòshì', 'or'], ['受了', 'shòu le', 'to receive; suffer'],
  ['逼迫', 'bīpò', 'persecution; pressure'], ['跌倒', 'diēdǎo', 'to stumble; fall away'],
  ['后来', 'hòulái', 'later'], ['世上', 'shìshàng', 'in the world'], ['思虑', 'sīlǜ', 'worries'],
  ['钱财', 'qiáncái', 'money; riches'], ['迷惑', 'míhuò', 'deception; temptation'],
  ['别样', 'biéyàng', 'other kinds'], ['私欲', 'sīyù', 'selfish desires'], ['进来', 'jìnlai', 'to come in'],
  ['不能', 'bùnéng', 'cannot'], ['好地', 'hǎo dì', 'good ground'], ['并且', 'bìngqiě', 'and; moreover'],
  ['拿', 'ná', 'to take; hold'], ['灯', 'dēng', 'lamp'], ['岂是', 'qǐshì', 'is it really?'],
  ['放在', 'fàng zài', 'to put on'], ['斗', 'dǒu', 'a measuring basket'], ['底下', 'dǐxia', 'underneath'],
  ['床', 'chuáng', 'bed'], ['灯台', 'dēngtái', 'lampstand'], ['掩藏', 'yǎncáng', 'to hide'],
  ['事', 'shì', 'thing; matter'], ['显出来', 'xiǎn chūlái', 'to be made visible'],
  ['隐瞒', 'yǐnmán', 'to conceal'], ['露出来', 'lù chūlái', 'to be revealed'],
  ['留心', 'liúxīn', 'to pay close attention'], ['什么', 'shénme', 'what'],
  ['量器', 'liàngqì', 'measuring tool'], ['量给', 'liàng gěi', 'to measure out to'],
  ['必', 'bì', 'certainly; surely'], ['多给', 'duō gěi', 'to give more'], ['还要', 'hái yào', 'will also; still will'],
  ['所有', 'suǒyǒu', 'all that one has'], ['夺去', 'duó qù', 'to take away'],
  ['国', 'guó', 'kingdom; country'], ['如同', 'rútóng', 'like; as if'], ['种', 'zhǒng', 'seed'],
  ['地上', 'dìshàng', 'on the ground'], ['黑夜', 'hēiyè', 'night'], ['睡觉', 'shuìjiào', 'to sleep'],
  ['白日', 'báirì', 'daytime'], ['这种', 'zhè zhǒng', 'this seed'], ['发芽', 'fā yá', 'to sprout'],
  ['渐长', 'jiàn zhǎng', 'to grow gradually'], ['那人', 'nà rén', 'that person'], ['如何', 'rúhé', 'how'],
  ['生', 'shēng', 'to grow; produce'], ['五谷', 'wǔgǔ', 'grain crops'], ['出于', 'chūyú', 'to come from'],
  ['自然', 'zìrán', 'naturally; by itself'], ['先', 'xiān', 'first'], ['后', 'hòu', 'after; later'],
  ['长穗', 'zhǎng suì', 'to grow ears of grain'], ['再后', 'zài hòu', 'after that'],
  ['穗上', 'suì shàng', 'on the ear of grain'], ['结成', 'jié chéng', 'to form'],
  ['饱满', 'bǎomǎn', 'full and ripe'], ['子粒', 'zǐlì', 'grain kernels'], ['谷', 'gǔ', 'grain'],
  ['熟了', 'shú le', 'has ripened'], ['镰刀', 'liándāo', 'sickle'], ['割', 'gē', 'to cut; harvest'],
  ['收成', 'shōuchéng', 'harvest'], ['到了', 'dào le', 'has arrived'], ['我们', 'wǒmen', 'we; us'],
  ['可用', 'kě yòng', 'can use'], ['比较', 'bǐjiào', 'to compare'], ['表明', 'biǎomíng', 'to show; make clear'],
  ['好像', 'hǎoxiàng', 'like; as if'], ['一粒', 'yí lì', 'one grain; one seed'],
  ['芥菜种', 'jiècài zhǒng', 'mustard seed'], ['种在', 'zhòng zài', 'to plant in'],
  ['地里', 'dìlǐ', 'in the ground'], ['虽', 'suī', 'although'], ['比', 'bǐ', 'than; compared with'],
  ['百种', 'bǎi zhǒng', 'all kinds of seeds'], ['小', 'xiǎo', 'small'], ['种上', 'zhòng shàng', 'to plant'],
  ['以后', 'yǐhòu', 'afterward'], ['各样', 'gèyàng', 'every kind'], ['菜', 'cài', 'vegetable; plant'],
  ['大', 'dà', 'big'], ['长出', 'zhǎng chū', 'to grow out'], ['大枝', 'dà zhī', 'large branches'],
  ['天上', 'tiānshàng', 'in the sky'], ['宿在', 'sù zài', 'to nest or rest in'],
  ['荫下', 'yìn xià', 'under the shade'], ['照', 'zhào', 'according to'], ['所能', 'suǒ néng', 'what one is able to'],
  ['讲道', 'jiǎngdào', 'to teach God’s message'], ['不用', 'bú yòng', 'not use'], ['讲给', 'jiǎng gěi', 'to explain to'],
  ['当', 'dāng', 'when; at'], ['那天', 'nà tiān', 'that day'], ['晚上', 'wǎnshang', 'evening'],
  ['渡到', 'dù dào', 'to cross over to'], ['那边', 'nàbian', 'the other side'], ['吧', 'ba', 'gentle command particle'],
  ['离开', 'líkāi', 'to leave'], ['仍在', 'réng zài', 'still in; remaining in'], ['船上', 'chuánshàng', 'on the boat'],
  ['一同', 'yìtóng', 'together'], ['带去', 'dài qù', 'to take along'], ['别的', 'biéde', 'other'],
  ['同行', 'tóngxíng', 'to travel together'], ['忽然', 'hūrán', 'suddenly'], ['起了', 'qǐ le', 'arose; began'],
  ['暴风', 'bàofēng', 'violent windstorm'], ['波浪', 'bōlàng', 'waves'], ['打入', 'dǎrù', 'to rush into'],
  ['船内', 'chuánnèi', 'inside the boat'], ['满了', 'mǎn le', 'became full'], ['水', 'shuǐ', 'water'],
  ['船尾', 'chuánwěi', 'stern of a boat'], ['枕着', 'zhěn zhe', 'resting on'], ['枕头', 'zhěntou', 'pillow'],
  ['叫醒', 'jiào xǐng', 'to wake someone'], ['夫子', 'fūzǐ', 'teacher; master'], ['丧命', 'sàngmìng', 'to perish; lose one’s life'],
  ['不顾', 'bù gù', 'not care about'], ['醒了', 'xǐng le', 'woke up'], ['斥责', 'chìzé', 'to rebuke'],
  ['风', 'fēng', 'wind'], ['向', 'xiàng', 'toward; to'], ['住了', 'zhù le', 'stop!'], ['静了', 'jìng le', 'be still!'],
  ['止住', 'zhǐ zhù', 'to stop'], ['大大地', 'dàdà de', 'greatly; very much'], ['平静', 'píngjìng', 'calm; peaceful'],
  ['为什么', 'wèishénme', 'why'], ['胆怯', 'dǎnqiè', 'afraid; timid'], ['还', 'hái', 'still; yet'],
  ['信心', 'xìnxīn', 'faith; trust'], ['惧怕', 'jùpà', 'to be very afraid'], ['彼此', 'bǐcǐ', 'one another'],
  ['到底', 'dàodǐ', 'after all; really'], ['听从', 'tīngcóng', 'to obey; listen to'],
].map(([term, pinyin, meaning]) => [term, {
  pinyin,
  meaning,
  usage: `本章中，${term} 表示 ${meaning}。`,
}]);

export default {
  id: 'mark-4',
  tabTitle: 'Mark 4',
  title: '马可福音 4',
  subtitle: '和合本简体中文（CUV） · Mark 4',

  vocab: ['撒种', '比喻', '神国', '奥秘', '领受', '结实', '留心', '信心', '胆怯'],

  paragraphs: [
    {
      id: 'p1',
      artCaption: '海边的撒种比喻 · The sower by the sea (v.1–9)',
      artAlt: '耶稣坐在船上，在海边向岸上的人群讲撒种的比喻。',
      artPrompt: 'A bright paper-cut collage for children, no text: Jesus teaching from a small boat near the shore while families listen; a farmer scatters seeds over a path, rocky ground, thorny soil, and rich soil. Bold layered shapes, warm sun, friendly faces.',
      verses: [
        { n: 1, tokens: ['耶稣', '又', '在', '海边', '教训', '人', '。', '有', '许多', '人', '到', '他', '那里', '聚集', '，', '他', '只得', '上船', '坐下', '。', '船', '在', '海里', '，', '众人', '都', '靠近', '海', '，', '站在', '岸上', '。'] },
        { n: 2, tokens: ['耶稣', '就', '用', '比喻', '教训', '他们', '许多', '道理', '。', '在', '教训', '之间', '，', '对', '他们', '说', '：'] },
        { n: 3, tokens: ['「', '你们', '听', '啊', '！', '有', '一个', '撒种', '的', '出去', '撒种', '。'] },
        { n: 4, tokens: ['撒', '的', '时候', '，', '有', '落在', '路旁', '的', '，', '飞鸟', '来', '吃尽', '了', '；'] },
        { n: 5, tokens: ['有', '落在', '土浅', '石头地', '上', '的', '，', '土', '既', '不', '深', '，', '发苗', '最快', '，'] },
        { n: 6, tokens: ['日头', '出来', '一晒', '，', '因为', '没有', '根', '，', '就', '枯干', '了', '；'] },
        { n: 7, tokens: ['有', '落在', '荆棘', '里', '的', '，', '荆棘', '长起来', '，', '把', '它', '挤住', '了', '，', '就', '不', '结实', '；'] },
        { n: 8, tokens: ['又', '有', '落在', '好土', '里', '的', '，', '就', '发生', '长大', '，', '结实', '有', '三十倍', '的', '，', '有', '六十倍', '的', '，', '有', '一百倍', '的', '」', '；'] },
        { n: 9, tokens: ['又', '说', '：', '「', '有', '耳', '可听', '的', '，', '就', '应当', '听', '！', '」'] },
      ],
    },
    {
      id: 'p2',
      artCaption: '种子和土壤 · Explaining the seed and soils (v.10–20)',
      artAlt: '耶稣和门徒坐在安静的山坡上，讲解种子落在不同土壤里的意思。',
      artPrompt: 'Gentle colored-pencil illustration for children, no text: Jesus sits with the twelve disciples on a quiet hillside and explains a seed growing in four small garden patches: path, rocks, thorns, and good earth. Soft textures and thoughtful expressions.',
      verses: [
        { n: 10, tokens: ['无人', '的', '时候', '，', '跟随', '耶稣', '的', '人', '和', '十二', '个', '门徒', '问', '他', '这', '比喻', '的', '意思', '。'] },
        { n: 11, tokens: ['耶稣', '对', '他们', '说', '：', '「', '神国', '的', '奥秘', '只', '叫', '你们', '知道', '，', '若是', '对', '外人', '讲', '，', '凡事', '就', '用', '比喻', '，'] },
        { n: 12, tokens: ['叫', '他们', '看', '是', '看见', '，', '却', '不', '晓得', '；', '听', '是', '听见', '，', '却', '不', '明白', '；', '恐怕', '他们', '回转', '过来', '，', '就', '得', '赦免', '。', '」'] },
        { n: 13, tokens: ['又', '对', '他们', '说', '：', '「', '你们', '不', '明白', '这', '比喻', '吗', '？', '这样', '怎能', '明白', '一切', '的', '比喻', '呢', '？'] },
        { n: 14, tokens: ['撒种之人', '所', '撒', '的', '就是', '道', '。'] },
        { n: 15, tokens: ['那', '撒在', '路旁', '的', '，', '就是', '人', '听', '了', '道', '，', '撒但', '立刻', '来', '，', '把', '撒在', '他', '心里', '的', '道', '夺了去', '。'] },
        { n: 16, tokens: ['那', '撒在', '石头地', '上', '的', '，', '就是', '人', '听', '了', '道', '，', '立刻', '欢喜', '领受', '，'] },
        { n: 17, tokens: ['但', '他', '心里', '没有', '根', '，', '不过', '是', '暂时', '的', '，', '及至', '为', '道', '遭了', '患难', '，', '或是', '受了', '逼迫', '，', '立刻', '就', '跌倒', '了', '。'] },
        { n: 18, tokens: ['还有', '那', '撒在', '荆棘', '里', '的', '，', '就是', '人', '听', '了', '道', '，'] },
        { n: 19, tokens: ['后来', '有', '世上', '的', '思虑', '、', '钱财', '的', '迷惑', '，', '和', '别样', '的', '私欲', '进来', '，', '把', '道', '挤住', '了', '，', '就', '不能', '结实', '。'] },
        { n: 20, tokens: ['那', '撒在', '好地', '上', '的', '，', '就是', '人', '听', '道', '，', '又', '领受', '，', '并且', '结实', '，', '有', '三十倍', '的', '，', '有', '六十倍', '的', '，', '有', '一百倍', '的', '。', '」'] },
      ],
    },
    {
      id: 'p3',
      artCaption: '灯要放在灯台上 · A lamp on its stand (v.21–25)',
      artAlt: '一盏小油灯放在灯台上，照亮屋子里认真聆听的孩子和大人。',
      artPrompt: 'Playful ink-and-watercolor comic panel, no text: a glowing little oil lamp on a tall lampstand lights a cozy ancient room while children and adults listen carefully. Clear expressive lines, blue night shadows, golden lamp glow.',
      verses: [
        { n: 21, tokens: ['耶稣', '又', '对', '他们', '说', '：', '「', '人', '拿', '灯', '来', '，', '岂是', '要', '放在', '斗', '底下', '，', '床', '底下', '，', '不', '放在', '灯台', '上', '吗', '？'] },
        { n: 22, tokens: ['因为', '掩藏', '的', '事', '，', '没有', '不', '显出来', '的', '；', '隐瞒', '的', '事', '，', '没有', '不', '露出来', '的', '。'] },
        { n: 23, tokens: ['有', '耳', '可听', '的', '，', '就', '应当', '听', '！', '」'] },
        { n: 24, tokens: ['又', '说', '：', '「', '你们', '所', '听', '的', '要', '留心', '。', '你们', '用', '什么', '量器', '量给', '人', '，', '也', '必', '用', '什么', '量器', '量给', '你们', '，', '并且', '要', '多给', '你们', '。'] },
        { n: 25, tokens: ['因为', '有', '的', '，', '还要', '给', '他', '；', '没有', '的', '，', '连', '他', '所有', '的', '也', '要', '夺去', '。', '」'] },
      ],
    },
    {
      id: 'p4',
      artCaption: '种子静静生长 · The seed grows quietly (v.26–29)',
      artAlt: '农夫睡觉又起床，田里的种子在日夜之间渐渐长成金色的麦穗。',
      artPrompt: 'Whimsical woodblock-print style for children, no text: a farmer sleeps beneath stars, wakes under sunlight, and watches a field change from tiny sprouts to full golden grain. Rich green, indigo, and ochre, simple carved textures.',
      verses: [
        { n: 26, tokens: ['又', '说', '：', '「', '神', '的', '国', '如同', '人', '把', '种', '撒在', '地上', '。'] },
        { n: 27, tokens: ['黑夜', '睡觉', '，', '白日', '起来', '，', '这种', '就', '发芽', '渐长', '，', '那人', '却', '不', '晓得', '如何', '这样', '。'] },
        { n: 28, tokens: ['地', '生', '五谷', '是', '出于', '自然', '的', '：', '先', '发苗', '，', '后', '长穗', '，', '再后', '穗上', '结成', '饱满', '的', '子粒', '；'] },
        { n: 29, tokens: ['谷', '既', '熟了', '，', '就', '用', '镰刀', '去', '割', '，', '因为', '收成', '的', '时候', '到了', '。', '」'] },
      ],
    },
    {
      id: 'p5',
      artCaption: '小小的芥菜种 · The mustard seed (v.30–34)',
      artAlt: '一粒小小的种子长成大大的植物，枝头有飞鸟停歇。',
      artPrompt: 'Soft clay-animation style illustration for children, no text: a tiny mustard seed in a child’s hand grows into a big leafy plant with wide branches, where small birds rest in the shade. Rounded tactile clay forms, joyful garden colors.',
      verses: [
        { n: 30, tokens: ['又', '说', '：', '「', '神', '的', '国', '，', '我们', '可用', '什么', '比较', '呢', '？', '可用', '什么', '比喻', '表明', '呢', '？'] },
        { n: 31, tokens: ['好像', '一粒', '芥菜种', '，', '种在', '地里', '的', '时候', '，', '虽', '比', '地上', '的', '百种', '都', '小', '，'] },
        { n: 32, tokens: ['但', '种上', '以后', '，', '就', '长起来', '，', '比', '各样', '的', '菜', '都', '大', '，', '又', '长出', '大枝', '来', '，', '甚至', '天上', '的', '飞鸟', '可以', '宿在', '它', '的', '荫下', '。', '」'] },
        { n: 33, tokens: ['耶稣', '用', '许多', '这样', '的', '比喻', '，', '照', '他们', '所能', '听', '的', '，', '对', '他们', '讲道', '。'] },
        { n: 34, tokens: ['若', '不用', '比喻', '，', '就', '不', '对', '他们', '讲', '；', '没有人', '的', '时候', '，', '就', '把', '一切', '的', '道', '讲给', '门徒', '听', '。'] },
      ],
    },
    {
      id: 'p6',
      artCaption: '风浪平静 · Jesus calms the storm (v.35–41)',
      artAlt: '夜里的小船遇到暴风，耶稣吩咐风浪安静，海面恢复平静。',
      artPrompt: 'Dramatic yet reassuring gouache night painting for children, no text: a small fishing boat rises on blue waves under dark clouds; Jesus calmly raises a hand and the storm settles into a glassy moonlit sea. Expressive brushwork, hopeful warm light.',
      verses: [
        { n: 35, tokens: ['当', '那天', '晚上', '，', '耶稣', '对', '门徒', '说', '：', '「', '我们', '渡到', '那边', '去', '吧', '。', '」'] },
        { n: 36, tokens: ['门徒', '离开', '众人', '，', '耶稣', '仍在', '船上', '，', '他们', '就', '把', '他', '一同', '带去', '；', '也', '有', '别的', '船', '和', '他', '同行', '。'] },
        { n: 37, tokens: ['忽然', '起了', '暴风', '，', '波浪', '打入', '船内', '，', '甚至', '船', '要', '满了', '水', '。'] },
        { n: 38, tokens: ['耶稣', '在', '船尾', '上', '，', '枕着', '枕头', '睡觉', '。', '门徒', '叫醒', '了', '他', '，', '说', '：', '「', '夫子', '！', '我们', '丧命', '，', '你', '不顾', '吗', '？', '」'] },
        { n: 39, tokens: ['耶稣', '醒了', '，', '斥责', '风', '，', '向', '海', '说', '：', '「', '住了', '吧', '！', '静了', '吧', '！', '」', '风', '就', '止住', '，', '大大地', '平静', '了', '。'] },
        { n: 40, tokens: ['耶稣', '对', '他们', '说', '：', '「', '为什么', '胆怯', '？', '你们', '还', '没有', '信心', '吗', '？', '」'] },
        { n: 41, tokens: ['他们', '就', '大大地', '惧怕', '，', '彼此', '说', '：', '「', '这', '到底', '是', '谁', '，', '连', '风', '和', '海', '也', '听从', '他', '了', '。', '」'] },
      ],
    },
  ],

  dict: {
    ...mark32035.dict,
    ...Object.fromEntries(mark4Entries),
  },
};
