// 马可福音 5 · 和合本简体中文（CUV）
// Scripture text is grouped into natural reading scenes; punctuation stays non-clickable.
//
// Each scene includes its illustration, with the original artPrompt and artAlt
// retained as the scene description and accessible image text.
import mark4 from './mark-4.js?v=6';

// [word, pinyin, meaning] — a fourth item replaces the generic usage note where
// the word carries the scene (a name, an illness, an Aramaic word Jesus used).
const mark5Entries = [
  ['格拉森', 'Gélāsēn', 'Gerasa; the Gerasenes', 'The far side of the lake — foreign country, away from home. 格拉森人的地方 = the region of the Gerasenes.'],
  ['地方', 'dìfang', 'place; region'], ['下船', 'xià chuán', 'to get out of a boat'],
  ['坟茔', 'fényíng', 'graves; tombs', 'Caves cut into the rock where the dead were laid. 住在坟茔里 = living among the graves — as far outside the town as a person could be.'],
  ['迎着', 'yíng zhe', 'coming to meet'], ['住在', 'zhù zài', 'to live in'],
  ['铁链', 'tiěliàn', 'iron chains'], ['屡次', 'lǚcì', 'again and again'],
  ['脚镣', 'jiǎoliào', 'leg irons'], ['捆锁', 'kǔnsuǒ', 'to bind and lock up'],
  ['竟', 'jìng', 'unexpectedly; actually'], ['挣断', 'zhèng duàn', 'to snap by struggling'],
  ['弄碎', 'nòng suì', 'to break into pieces'], ['总', 'zǒng', 'always; in the end'],
  ['制伏', 'zhìfú', 'to subdue; bring under control', '没有人能制伏他 = no one was strong enough to control him. The whole town had tried; only Jesus could.'],
  ['昼夜', 'zhòuyè', 'day and night'], ['山中', 'shān zhōng', 'in the hills'],
  ['喊叫', 'hǎnjiào', 'to shout; cry out'], ['石头', 'shítou', 'stone'], ['砍', 'kǎn', 'to cut; strike'],
  ['远远地', 'yuǎnyuǎn de', 'from far away'], ['跑过去', 'pǎo guòqù', 'to run over'],
  ['拜', 'bài', 'to bow down before'], ['大声', 'dàshēng', 'loudly'], ['呼叫', 'hūjiào', 'to call out'],
  ['至高', 'zhìgāo', 'most high'], ['与', 'yǔ', 'with'],
  ['相干', 'xiānggān', 'to have to do with', '我与你有什么相干 = what do you want with me? An old way of asking "why are you bothering me?"'],
  ['指着', 'zhǐ zhe', 'pointing to; in the name of'],
  ['恳求', 'kěnqiú', 'to beg earnestly', 'Three people beg in this chapter: the spirits, the healed man, and Jairus. Jesus answers each of them differently.'],
  ['受苦', 'shòu kǔ', 'to suffer'], ['是因', 'shì yīn', 'this was because'], ['曾', 'céng', 'had already'],
  ['这人', 'zhè rén', 'this man'], ['身上', 'shēnshang', "on someone's body"],
  ['名叫', 'míng jiào', 'to be named'],
  ['群', 'qún', 'a crowd; Legion', 'A Roman legion was thousands of soldiers. As a name it means: there are far too many of us to count.'],
  ['缘故', 'yuángù', 'reason'], ['再三地', 'zàisān de', 'again and again'], ['求', 'qiú', 'to beg; ask'],
  ['山坡', 'shānpō', 'hillside'], ['大群', 'dà qún', 'a large herd'], ['猪', 'zhū', 'pig'],
  ['吃食', 'chī shí', 'to feed'], ['鬼', 'guǐ', 'evil spirit'], ['央求', 'yāngqiú', 'to plead'],
  ['往', 'wǎng', 'toward; into'], ['猪群', 'zhū qún', 'the herd of pigs'], ['准', 'zhǔn', 'to allow'],
  ['进入', 'jìnrù', 'to enter'], ['于是', 'yúshì', 'so; and then'], ['闯下', 'chuǎng xià', 'to rush down'],
  ['山崖', 'shānyá', 'cliff'], ['投在', 'tóu zài', 'to plunge into'], ['淹死', 'yān sǐ', 'to drown'],
  ['数目', 'shùmù', 'number; count'], ['约', 'yuē', 'about; roughly'], ['二千', 'èrqiān', 'two thousand'],
  ['放猪', 'fàng zhū', 'to herd pigs'], ['逃跑', 'táopǎo', 'to run away'], ['城里', 'chénglǐ', 'in the town'],
  ['乡下', 'xiāngxia', 'the countryside'], ['从前', 'cóngqián', 'before; formerly'],
  ['群鬼', 'qún guǐ', 'the many evil spirits'], ['附', 'fù', 'to attach to; possess'],
  ['穿上', 'chuān shàng', 'to put on (clothes)'], ['衣服', 'yīfu', 'clothes'],
  ['害怕', 'hàipà', 'to be afraid'], ['这事', 'zhè shì', 'this thing that happened'],
  ['将', 'jiāng', 'takes the object in front of the verb'],
  ['鬼附之人', 'guǐ fù zhī rén', 'the man the spirits had possessed'],
  ['遇见', 'yùjiàn', 'to meet with; happen to'], ['境界', 'jìngjiè', 'territory; district'],
  ['不许', 'bùxǔ', 'to not allow'], ['回家', 'huí jiā', 'to go home'], ['主', 'zhǔ', 'the Lord'],
  ['何等', 'héděng', 'how great'],
  ['怜悯', 'liánmǐn', 'to have mercy on', 'Jesus tells him to say two things at home: 主为你所做的 (what the Lord did) and 是怎样怜悯你 (how kind he was in doing it).'],
  ['走', 'zǒu', 'to go; walk'],
  ['低加坡里', 'Dījiāpōlǐ', 'the Decapolis', 'The Ten Towns, a whole region east of the lake. One man tells it everywhere — the first missionary in Mark is someone sent home.'],
  ['传扬', 'chuányáng', 'to spread the news'], ['希奇', 'xīqí', 'amazed'],
  ['坐船', 'zuò chuán', 'to go by boat'], ['正在', 'zhèngzài', 'to be right at'],
  ['管会堂', 'guǎn huìtáng', 'in charge of the synagogue'],
  ['睚鲁', 'Yálǔ', 'Jairus', 'A synagogue leader — an important man who kneels in the dirt in front of Jesus for his daughter.'],
  ['见', 'jiàn', 'to see; meet'], ['脚前', 'jiǎo qián', "at someone's feet"],
  ['小女儿', 'xiǎo nǚ’ér', 'little daughter'], ['快要', 'kuàiyào', 'about to'], ['死', 'sǐ', 'to die'],
  ['按手', 'àn shǒu', 'to lay hands on'], ['她', 'tā', 'she; her'], ['使', 'shǐ', 'to cause; make'],
  ['痊愈', 'quányù', 'to be healed', 'Used twice in this chapter — for the woman who touches his clothes and by Jairus for his daughter. Both get it.'],
  ['得以', 'déyǐ', 'so as to be able to'], ['活', 'huó', 'to live'], ['同去', 'tóng qù', 'to go together'],
  ['女人', 'nǚrén', 'woman'], ['患', 'huàn', 'to suffer from (an illness)'], ['年', 'nián', 'year'],
  ['血漏', 'xuè lòu', 'bleeding that would not stop', 'Twelve years of it — exactly as long as Jairus’s daughter had been alive. Mark puts the two stories inside each other on purpose.'],
  ['好些', 'hǎoxiē', 'quite a few'], ['医生', 'yīshēng', 'doctor'], ['手里', 'shǒulǐ', 'in the hands of'],
  ['受', 'shòu', 'to suffer; receive'], ['苦', 'kǔ', 'suffering; hardship'],
  ['花尽', 'huā jìn', 'to spend everything'], ['一点', 'yìdiǎn', 'a bit'],
  ['不见好', 'bú jiàn hǎo', 'no better'], ['病势', 'bìngshì', 'the illness'],
  ['反倒', 'fǎndào', 'instead; on the contrary'], ['更重', 'gèng zhòng', 'worse; heavier'],
  ['后头', 'hòutou', 'behind'], ['杂在', 'zá zài', 'to mix in among'], ['中间', 'zhōngjiān', 'in the middle of'],
  ['衣裳', 'yīshang', 'clothes'], ['源头', 'yuántóu', 'the source'], ['干', 'gān', 'dried up'],
  ['觉得', 'juéde', 'to feel'], ['好', 'hǎo', 'well; better'], ['顿时', 'dùnshí', 'at once'],
  ['能力', 'nénglì', 'power'], ['转过来', 'zhuǎn guòlái', 'to turn around'], ['成', 'chéng', 'to happen; be done'],
  ['恐惧', 'kǒngjù', 'fear'], ['战兢', 'zhànjīng', 'trembling'], ['跟前', 'gēnqián', 'in front of'],
  ['实情', 'shíqíng', 'the whole truth'], ['全', 'quán', 'completely; all'], ['女儿', 'nǚ’ér', 'daughter'],
  ['信', 'xìn', 'faith; to believe', '你的信救了你 = your faith has healed you. The same 信 Jesus asks of Jairus one verse later: 只要信.'],
  ['救', 'jiù', 'to save'], ['平平安安地', 'píngpíng’ān’ān de', 'in peace'], ['回去', 'huíqù', 'to go back'],
  ['说话', 'shuōhuà', 'to speak'], ['有人', 'yǒu rén', 'someone'], ['何必', 'hébì', 'why bother'],
  ['劳动', 'láodòng', 'to trouble (someone)'], ['先生', 'xiānsheng', 'teacher; sir'], ['怕', 'pà', 'to be afraid'],
  ['只要', 'zhǐyào', 'only; just'], ['带着', 'dài zhe', 'to take along'], ['别人', 'biérén', 'other people'],
  ['乱嚷', 'luàn rǎng', 'a noisy commotion'], ['哭泣', 'kūqì', 'to weep'], ['哀号', 'āiháo', 'to wail'],
  ['进到', 'jìn dào', 'to go into'], ['里面', 'lǐmiàn', 'inside'], ['孩子', 'háizi', 'child'],
  ['不是', 'bú shì', 'is not'], ['睡着', 'shuì zháo', 'asleep'], ['嗤笑', 'chīxiào', 'to laugh scornfully'],
  ['撵', 'niǎn', 'to send out; put out'], ['父母', 'fùmǔ', 'parents'],
  ['所在', 'suǒzài', 'the place where someone is'], ['拉着', 'lā zhe', 'holding; taking by the hand'],
  ['大利大', 'Dàlìdà', 'Talitha', 'Aramaic — the everyday language Jesus spoke at home. Mark keeps his exact words and then translates them.'],
  ['古米', 'Gǔmǐ', 'koum — get up'], ['翻出来', 'fān chūlái', 'translated'],
  ['闺女', 'guīnü', 'girl; daughter'], ['立时', 'lìshí', 'at once'], ['惊奇', 'jīngqí', 'amazed'],
  ['已经', 'yǐjīng', 'already'], ['岁', 'suì', 'years old'], ['切切地', 'qièqiè de', 'earnestly; strictly'],
  ['东西', 'dōngxi', 'something (to eat)'],
].map(([term, pinyin, meaning, usage]) => [term, {
  pinyin,
  meaning,
  usage: usage || `本章中，${term} 表示 ${meaning}。`,
}]);

export default {
  id: 'mark-5',
  tabTitle: 'Mark 5',
  title: '马可福音 5',
  subtitle: '和合本简体中文（CUV） · Mark 5',
  // YouVersion passage id for the English parallel: <book>.<chapter>.<verse>.
  passage: { book: 'MRK', chapter: 5 },

  // Recorded narration: one slow Mandarin file per verse (fangfang, CosyVoice 3
  // at speed 0.85 — generated in the private lucas-academy-media repo). The
  // player derives <dir>/verse-NN.mp3 and falls back to speech synthesis if a
  // file is missing.
  audio: { dir: 'assets/audio/mark-5' },

  vocab: ['污鬼', '坟茔', '制伏', '恳求', '怜悯', '传扬', '血漏', '痊愈', '俯伏', '信'],

  paragraphs: [
    {
      id: 'p1',
      artCaption: '坟茔里的人 · The man among the tombs (v.1–8)',
      artImage: 'assets/illustrations/mark-5-01-08.jpg',
      artAlt: '清晨的岩石山坡上有石洞坟茔，一个孤单的人朝刚下船的耶稣跑来，地上散着断开的铁链。',
      artPrompt: 'Warm children\'s picture-book illustration, no text, nothing frightening: dawn on a rocky hillside above a lake, cave tombs in the rock, broken chains lying on the ground, a lonely ragged man running down toward Jesus who has just stepped out of a small boat. Gentle faces, hopeful morning light.',
      verses: [
        { n: 1, tokens: ['他们','来到','海','那边','格拉森','人','的','地方','。'] },
        { n: 2, tokens: ['耶稣','一','下船','，','就','有','一个','被','污鬼','附着','的','人','从','坟茔','里','出来','迎着','他','。'] },
        { n: 3, tokens: ['那人','常','住在','坟茔','里','，','没有','人','能','捆住','他','，','就是','用','铁链','也','不能','；'] },
        { n: 4, tokens: ['因为','人','屡次','用','脚镣','和','铁链','捆锁','他','，','铁链','竟','被','他','挣断','了','，','脚镣','也','被','他','弄碎','了','；','总','没有','人','能','制伏','他','。'] },
        { n: 5, tokens: ['他','昼夜','常','在','坟茔','里','和','山中','喊叫','，','又','用','石头','砍','自己','。'] },
        { n: 6, tokens: ['他','远远地','看见','耶稣','，','就','跑过去','拜','他','，'] },
        { n: 7, tokens: ['大声','呼叫','说','：','「','至高','神','的','儿子','耶稣','，','我','与','你','有','什么','相干','？','我','指着','神','恳求','你','，','不要','叫','我','受苦','！','」'] },
        { n: 8, tokens: ['是因','耶稣','曾','吩咐','他','说','：','「','污鬼','啊','，','从','这人','身上','出来','吧','！','」'] },
      ],
    },
    {
      id: 'p2',
      artCaption: '「群」和猪群 · Legion and the pigs (v.9–13)',
      artImage: 'assets/illustrations/mark-5-09-13.jpg',
      artAlt: '山坡上一大群猪在吃食，远处的海边站着耶稣和那个跪着的人。',
      artPrompt: 'Bright paper-cut collage for children, no text: a green hillside above a blue lake with a big herd of pigs feeding, and further down the slope Jesus standing calmly beside a kneeling man. Bold layered shapes, no scary or violent detail.',
      verses: [
        { n: 9, tokens: ['耶稣','问','他','说','：','「','你','名叫','什么','？','」','回答','说','：','「','我','名叫','『','群','』','，','因为','我们','多','的','缘故','」','；'] },
        { n: 10, tokens: ['就','再三地','求','耶稣','，','不要','叫','他们','离开','那','地方','。'] },
        { n: 11, tokens: ['在','那里','山坡','上','，','有','一','大群','猪','吃食','；'] },
        { n: 12, tokens: ['鬼','就','央求','耶稣','说','：','「','求','你','打发','我们','往','猪群','里','，','附着','猪','去','。','」'] },
        { n: 13, tokens: ['耶稣','准','了','他们','，','污鬼','就','出来','，','进入','猪','里','去','。','于是','那','群','猪','闯下','山崖','，','投在','海里','，','淹死','了','。','猪','的','数目','约','有','二千','。'] },
      ],
    },
    {
      id: 'p3',
      artCaption: '回家去传扬 · Sent home to tell (v.14–20)',
      artImage: 'assets/illustrations/mark-5-14-20.jpg',
      artAlt: '那人穿好衣服、心里明白过来，坐在耶稣旁边；城里的人远远站着观看。',
      artPrompt: 'Gentle colored-pencil illustration for children, no text: the once-wild man now washed, dressed and calm, sitting beside Jesus on the shore, while townspeople stand at a distance watching, and in the corner the same man later talking happily to families in a village. Soft textures, kind expressions.',
      verses: [
        { n: 14, tokens: ['放猪','的','就','逃跑','了','，','去','告诉','城里','和','乡下','的','人','。','众人','就','来','，','要','看','是','什么','事','。'] },
        { n: 15, tokens: ['他们','来到','耶稣','那里','，','看见','那','被','鬼','附着','的','人','，','就是','从前','被','群鬼','所','附','的','，','坐着','，','穿上','衣服','，','心里','明白','过来','，','他们','就','害怕','。'] },
        { n: 16, tokens: ['看见','这事','的','，','便','将','鬼附之人','所','遇见','的','和','那','群','猪','的','事','都','告诉','了','众人','；'] },
        { n: 17, tokens: ['众人','就','央求','耶稣','离开','他们','的','境界','。'] },
        { n: 18, tokens: ['耶稣','上船','的','时候','，','那','从前','被','鬼','附着','的','人','恳求','和','耶稣','同在','。'] },
        { n: 19, tokens: ['耶稣','不许','，','却','对','他','说','：','「','你','回家','去','，','到','你','的','亲属','那里','，','将','主','为','你','所','做','的','是','何等','大','的','事','，','是','怎样','怜悯','你','，','都','告诉','他们','。','」'] },
        { n: 20, tokens: ['那人','就','走','了','，','在','低加坡里','传扬','耶稣','为','他','做','了','何等','大','的','事','，','众人','就','都','希奇','。'] },
      ],
    },
    {
      id: 'p4',
      artCaption: '睚鲁的恳求 · Jairus kneels (v.21–24)',
      artImage: 'assets/illustrations/mark-5-21-24.jpg',
      artAlt: '海边挤满了人，管会堂的睚鲁跪在耶稣脚前恳求他。',
      artPrompt: 'Ink-and-watercolor scene for children, no text: a crowded lakeshore, a well-dressed synagogue leader kneeling at Jesus\'s feet with both hands raised in pleading, the crowd pressing in around them. Expressive lines, warm afternoon colors, urgent but not frightening.',
      verses: [
        { n: 21, tokens: ['耶稣','坐船','又','渡到','那边','去','，','就','有','许多','人','到','他','那里','聚集','；','他','正在','海边','上','。'] },
        { n: 22, tokens: ['有','一个','管会堂','的','人','，','名叫','睚鲁','，','来','见','耶稣','，','就','俯伏','在','他','脚前','，'] },
        { n: 23, tokens: ['再三地','求','他','，','说','：','「','我','的','小女儿','快要','死','了','，','求','你','去','按手','在','她','身上','，','使','她','痊愈','，','得以','活','了','。','」'] },
        { n: 24, tokens: ['耶稣','就','和','他','同去','。','有','许多','人','跟随','拥挤','他','。'] },
      ],
    },
    {
      id: 'p5',
      artCaption: '摸耶稣衣裳的女人 · The woman who touched his cloak (v.25–34)',
      artImage: 'assets/illustrations/mark-5-25-34.jpg',
      artAlt: '拥挤的人群中，一个女人从后面伸手轻轻摸耶稣的衣裳，耶稣转过身来看她。',
      artPrompt: 'Tender children\'s illustration, no text: inside a pressing crowd, a woman reaches out from behind and touches the hem of Jesus\'s robe with her fingertips; Jesus is turning around to look for her with a kind face. Soft golden light on the two of them, the crowd in gentle shadow.',
      verses: [
        { n: 25, tokens: ['有','一个','女人','，','患','了','十二','年','的','血漏','，'] },
        { n: 26, tokens: ['在','好些','医生','手里','受','了','许多','的','苦','，','又','花尽','了','她','所有','的','，','一点','也','不见好','，','病势','反倒','更重','了','。'] },
        { n: 27, tokens: ['她','听见','耶稣','的','事','，','就','从','后头','来','，','杂在','众人','中间','，','摸','耶稣','的','衣裳','，'] },
        { n: 28, tokens: ['意思','说','：','「','我','只','摸','他','的','衣裳','，','就','必','痊愈','。','」'] },
        { n: 29, tokens: ['于是','她','血漏','的','源头','立刻','干','了','；','她','便','觉得','身上','的','灾病','好','了','。'] },
        { n: 30, tokens: ['耶稣','顿时','心里','觉得','有','能力','从','自己','身上','出去','，','就','在','众人','中间','转过来','，','说','：','「','谁','摸','我','的','衣裳','？','」'] },
        { n: 31, tokens: ['门徒','对','他','说','：','「','你','看','众人','拥挤','你','，','还','说','『','谁','摸','我','』','吗','？','」'] },
        { n: 32, tokens: ['耶稣','周围','观看','，','要','见','做','这事','的','女人','。'] },
        { n: 33, tokens: ['那','女人','知道','在','自己','身上','所','成','的','事','，','就','恐惧','战兢','，','来','俯伏','在','耶稣','跟前','，','将','实情','全','告诉','他','。'] },
        { n: 34, tokens: ['耶稣','对','她','说','：','「','女儿','，','你','的','信','救','了','你','，','平平安安地','回去','吧','！','你','的','灾病','痊愈','了','。','」'] },
      ],
    },
    {
      id: 'p6',
      artCaption: '「大利大，古米！」 · Talitha koum (v.35–43)',
      artImage: 'assets/illustrations/mark-5-35-43.jpg',
      artAlt: '安静的房间里，耶稣拉着小女孩的手，女孩正要起来，父母在旁边惊奇地看着。',
      artPrompt: 'Quiet, luminous children\'s illustration, no text: a small bedroom in an ancient house at dawn, Jesus holding a twelve-year-old girl\'s hand as she sits up in bed, her mother and father watching in wonder, three disciples in the doorway. Peaceful colors, morning light through the window, joy rather than sorrow.',
      verses: [
        { n: 35, tokens: ['还','说话','的','时候','，','有人','从','管会堂','的','家里','来','，','说','：','「','你','的','女儿','死','了','，','何必','还','劳动','先生','呢','？','」'] },
        { n: 36, tokens: ['耶稣','听见','所','说','的','话','，','就','对','管会堂','的','说','：','「','不要','怕','，','只要','信','！','」'] },
        { n: 37, tokens: ['于是','带着','彼得','、','雅各','，','和','雅各','的','兄弟','约翰','同去','，','不许','别人','跟随','他','。'] },
        { n: 38, tokens: ['他们','来到','管会堂','的','家里','；','耶稣','看见','那里','乱嚷','，','并','有人','大大地','哭泣','哀号','，'] },
        { n: 39, tokens: ['进到','里面','，','就','对','他们','说','：','「','为什么','乱嚷','哭泣','呢','？','孩子','不是','死','了','，','是','睡着','了','。','」'] },
        { n: 40, tokens: ['他们','就','嗤笑','耶稣','。','耶稣','把','他们','都','撵','出去','，','就','带着','孩子','的','父母','和','跟随','的','人','进','了','孩子','所在','的','地方','，'] },
        { n: 41, tokens: ['就','拉着','孩子','的','手','，','对','她','说','：','「','大利大','，','古米','！','」','（','翻出来','就是','说','：','「','闺女','，','我','吩咐','你','起来','！','」','）'] },
        { n: 42, tokens: ['那','闺女','立时','起来','走','。','他们','就','大大地','惊奇','；','闺女','已经','十二','岁','了','。'] },
        { n: 43, tokens: ['耶稣','切切地','嘱咐','他们','，','不要','叫','人','知道','这事','，','又','吩咐','给','她','东西','吃','。'] },
      ],
    },
  ],

  // Plain-English notes, written by hand: the API sends scripture text only.
  explain: {
    1: "Jesus and the disciples land on the far side of the lake, in the country of the Gerasenes — foreign ground, away from home.",
    2: "The moment he steps out of the boat, a man comes out of the tombs to meet him with an unclean spirit in him.",
    3: "The man lives among the graves. Nobody can tie him down any more, not even with chains.",
    4: "Chains and leg irons had been tried again and again; he snapped them every time. No one was strong enough to control him.",
    5: "Night and day he cries out among the tombs and in the hills, and hurts himself with stones. This is the loneliest verse in the chapter.",
    6: "He sees Jesus from far off, runs to him, and bows down in front of him.",
    7: "The spirit shouts: Jesus, Son of the Most High God, what do you want with me? Don't make me suffer! Even it knows exactly who Jesus is.",
    8: "It says that because Jesus had already told it: 「污鬼啊，从这人身上出来吧！」 Come out of this man.",
    9: "Jesus asks its name. 「群」 — Legion — because there are so many of them inside one person.",
    10: "They beg him again and again not to send them out of that region.",
    11: "On the hillside nearby a large herd of pigs is feeding.",
    12: "The spirits ask to be sent into the pigs instead.",
    13: "Jesus lets them, and the herd — about two thousand — rushes down the cliff into the lake. One man mattered more than all of it.",
    14: "The men looking after the pigs run off and tell the town and the countryside, and everybody comes out to see.",
    15: "They find the man who had the legion sitting there, dressed, 心里明白过来 — in his right mind — and that frightens them.",
    16: "The people who saw it tell the crowd everything: what happened to the man, and what happened to the pigs.",
    17: "So the crowd asks Jesus to leave their district. They would rather keep their pigs than keep him.",
    18: "As Jesus is getting into the boat, the healed man begs to come with him.",
    19: "Jesus says no, and gives him a harder job: go home to your own family and tell them what the Lord did for you, and how kind he was.",
    20: "So the man tells it all through the Decapolis (低加坡里, the Ten Towns), and everyone is amazed. The first person Mark sends out is someone sent home.",
    21: "Back across the lake, a big crowd gathers around Jesus at the shore.",
    22: "睚鲁 (Jairus), one of the leaders of the synagogue, comes and falls down at his feet.",
    23: "He begs over and over: my little daughter is dying — come and put your hands on her so she will live.",
    24: "Jesus goes with him, and the crowd presses in on every side. From here the chapter tells two stories at once.",
    25: "In that crowd is a woman who has been bleeding for twelve years — exactly as long as Jairus's daughter has been alive.",
    26: "Doctors had cost her everything she had, and she only got worse.",
    27: "She comes up behind him in the crowd and touches his clothes.",
    28: "Her thought is simple: 我只摸他的衣裳，就必痊愈 — if I only touch his clothes, I will be well.",
    29: "The bleeding stops at once, and she can feel in her body that the illness is gone.",
    30: "Jesus feels power go out of him, turns round in the crowd and asks: who touched my clothes?",
    31: "The disciples think it is a strange question — the whole crowd is pressing against you!",
    32: "But Jesus keeps looking until he finds her. He wants the person, not just the healing.",
    33: "She comes trembling, kneels in front of him, and tells him the whole truth.",
    34: "「女儿，你的信救了你」 — daughter, your faith has healed you. Go in peace. He gives her a name in his family, not only a cure.",
    35: "While he is still speaking, someone comes from Jairus's house: your daughter is dead, why trouble the teacher any more?",
    36: "Jesus hears it and says to Jairus: 不要怕，只要信 — don't be afraid, only believe.",
    37: "He takes only Peter, James and John with him the rest of the way.",
    38: "At the house there is a commotion, with people weeping and wailing loudly.",
    39: "He asks why all the noise — the child is not dead but asleep.",
    40: "They laugh at him. He puts them all outside and takes the parents and his three disciples in to where the child is.",
    41: "He takes her hand and says 「大利大，古米！」 — Aramaic for: little girl, I say to you, get up.",
    42: "She gets up straight away and walks about. She is twelve years old, and everyone is astonished.",
    43: "He tells them firmly not to spread it around — and then, very practically, says to give her something to eat.",
  },

  dict: {
    ...mark4.dict,
    ...Object.fromEntries(mark5Entries),
  },
};
