// 马可福音 3:1–19 · 和合本（神版）
// tokens: one word per clickable unit; punctuation stays as its own (non-clickable) token.
// artPrompt: kept as data for generating the paragraph illustration later.
export default {
  id: 'mark-3',
  tabTitle: 'Mark 3',
  title: '马可福音 3:1–19',
  subtitle: '和合本（神版） · Mark 3:1–19',

  paragraphs: [
    {
      id: 'p1',
      artCaption: '安息日治病 · Healing on the Sabbath (v.1–6)',
      artPrompt:
        'Warm watercolor storybook illustration, no text: inside an ancient stone synagogue, ' +
        'Jesus stands beside a man stretching out his withered hand, which is being restored; ' +
        'stern Pharisees watch from the side. Kid-friendly.',
      verses: [
        { n: 1, tokens: ['耶稣', '又', '进', '了', '会堂', '，', '在', '那里', '有', '一个', '人', '枯干', '了', '一只', '手', '。'] },
        { n: 2, tokens: ['众人', '窥探', '耶稣', '，', '在', '安息日', '医治', '不', '医治', '，', '意思', '是', '要', '控告', '耶稣', '。'] },
        { n: 3, tokens: ['耶稣', '对', '那', '枯干', '一只', '手', '的', '人', '说', '：', '「', '起来', '，', '站', '在', '当中', '。', '」'] },
        { n: 4, tokens: ['又', '问', '众人', '说', '：', '「', '在', '安息日', '行善', '行恶', '，', '救命', '害命', '，', '哪样', '是', '可以', '的', '呢', '？', '」', '他们', '都', '不', '作声', '。'] },
        { n: 5, tokens: ['耶稣', '怒目', '周围', '看', '他们', '，', '忧愁', '他们', '的', '心', '刚硬', '，', '就', '对', '那', '人', '说', '：', '「', '伸出', '手', '来', '！', '」', '他', '把', '手', '一', '伸', '，', '手', '就', '复了原', '。'] },
        { n: 6, tokens: ['法利赛人', '出去', '，', '同', '希律', '一党', '的', '人', '商议', '怎样', '可以', '除灭', '耶稣', '。'] },
      ],
    },
    {
      id: 'p2',
      artCaption: '海边的人群 · Crowds by the sea (v.7–12)',
      artPrompt:
        'Warm watercolor storybook illustration, no text: Jesus and his disciples by the Sea of Galilee, ' +
        'huge crowds arriving from every direction, a small boat waiting near the shore, ' +
        'people reaching out to touch him. Kid-friendly.',
      verses: [
        { n: 7, tokens: ['耶稣', '和', '门徒', '退到', '海边', '去', '，', '有', '许多', '人', '从', '加利利', '跟随', '他', '。'] },
        { n: 8, tokens: ['还有', '许多', '人', '听见', '他', '所', '做', '的', '大事', '，', '就', '从', '犹太', '、', '耶路撒冷', '、', '以土买', '、', '约旦河', '外', '，', '并', '泰尔', '、', '西顿', '的', '四方', '来到', '他', '那里', '。'] },
        { n: 9, tokens: ['他', '因为', '人', '多', '，', '就', '吩咐', '门徒', '叫', '一只', '小船', '伺候', '着', '，', '免得', '众人', '拥挤', '他', '。'] },
        { n: 10, tokens: ['他', '治好', '了', '许多', '人', '，', '所以', '凡', '有', '灾病', '的', '，', '都', '挤进来', '要', '摸', '他', '。'] },
        { n: 11, tokens: ['污鬼', '无论', '何时', '看见', '他', '，', '就', '俯伏', '在', '他', '面前', '，', '喊', '着', '说', '：', '「', '你', '是', '神', '的', '儿子', '。', '」'] },
        { n: 12, tokens: ['耶稣', '再三', '地', '嘱咐', '他们', '，', '不要', '把', '他', '显露', '出来', '。'] },
      ],
    },
    {
      id: 'p3',
      artCaption: '山上设立十二使徒 · Choosing the Twelve (v.13–19)',
      artPrompt:
        'Warm watercolor storybook illustration, no text: Jesus on a green mountain calling twelve men ' +
        'to himself; the twelve gathered around him under a bright sky. Kid-friendly.',
      verses: [
        { n: 13, tokens: ['耶稣', '上', '了', '山', '，', '随', '自己', '的', '意思', '叫', '人', '来', '；', '他们', '便', '来到', '他', '那里', '。'] },
        { n: 14, tokens: ['他', '就', '设立', '十二', '个', '人', '，', '要', '他们', '常', '和', '自己', '同在', '，', '也', '要', '差', '他们', '去', '传道', '，'] },
        { n: 15, tokens: ['并', '给', '他们', '权柄', '赶鬼', '。'] },
        { n: 16, tokens: ['这', '十二', '个', '人', '有', '西门', '（', '耶稣', '又', '给', '他', '起名', '叫', '彼得', '）', '，'] },
        { n: 17, tokens: ['还有', '西庇太', '的', '儿子', '雅各', '和', '雅各', '的', '兄弟', '约翰', '（', '又', '给', '这', '两个', '人', '起名', '叫', '半尼其', '，', '就是', '雷子', '的', '意思', '）', '，'] },
        { n: 18, tokens: ['又', '有', '安得烈', '、', '腓力', '、', '巴多罗买', '、', '马太', '、', '多马', '、', '亚勒腓', '的', '儿子', '雅各', '，', '和', '达太', '，', '并', '奋锐党', '的', '西门', '，'] },
        { n: 19, tokens: ['还有', '卖', '耶稣', '的', '加略人', '犹大', '。'] },
      ],
    },
  ],

  dict: {
    // ---- names & Bible terms ----
    '耶稣': { pinyin: 'Yēsū', meaning: 'Jesus', usage: 'The name of Jesus — the main person of this story. Chinese Bible names copy the sound of the original name.' },
    '会堂': { pinyin: 'huìtáng', meaning: 'synagogue', usage: '会 (gather) + 堂 (hall) = the hall where Jewish people gathered to worship. 进了会堂 = went into the synagogue.' },
    '安息日': { pinyin: 'Ānxīrì', meaning: 'the Sabbath', usage: '安息 (rest) + 日 (day) = the rest day, when no work was allowed. 在安息日 = on the Sabbath.' },
    '法利赛人': { pinyin: 'Fǎlìsàirén', meaning: 'the Pharisees', usage: 'A group of very strict religious leaders. The ending 人 means "people (of that group)".' },
    '希律': { pinyin: 'Xīlǜ', meaning: 'Herod', usage: 'King Herod. 希律一党的人 = the people of Herod\'s party (the Herodians).' },
    '加利利': { pinyin: 'Jiālìlì', meaning: 'Galilee', usage: 'The region where Jesus lived and taught. 从加利利 = from Galilee.' },
    '犹太': { pinyin: 'Yóutài', meaning: 'Judea', usage: 'The region around Jerusalem. Here it is one of the places people came from.' },
    '耶路撒冷': { pinyin: 'Yēlùsālěng', meaning: 'Jerusalem', usage: 'The most important city, where the temple was.' },
    '以土买': { pinyin: 'Yǐtǔmǎi', meaning: 'Idumea', usage: 'A region south of Judea — people came even from this far place.' },
    '约旦河': { pinyin: 'Yuēdànhé', meaning: 'the Jordan River', usage: '河 = river. 约旦河外 = the land beyond the Jordan River.' },
    '泰尔': { pinyin: 'Tài\'ěr', meaning: 'Tyre', usage: 'A seaside city to the north. People came from around Tyre and Sidon too.' },
    '西顿': { pinyin: 'Xīdùn', meaning: 'Sidon', usage: 'Another seaside city near Tyre, far to the north.' },
    '污鬼': { pinyin: 'wūguǐ', meaning: 'unclean spirits', usage: '污 (dirty, unclean) + 鬼 (spirit, demon). The unclean spirits fell down before Jesus.' },
    '神': { pinyin: 'Shén', meaning: 'God', usage: '神的儿子 = the Son of God — what the spirits shouted about Jesus.' },
    '西门': { pinyin: 'Xīmén', meaning: 'Simon', usage: 'Two apostles share this name: Simon (renamed Peter) and 奋锐党的西门 (Simon the Zealot).' },
    '彼得': { pinyin: 'Bǐdé', meaning: 'Peter', usage: 'The new name Jesus gave Simon. 起名叫彼得 = named him Peter (the name means "rock").' },
    '西庇太': { pinyin: 'Xībìtài', meaning: 'Zebedee', usage: 'The father of James and John. 西庇太的儿子雅各 = James the son of Zebedee.' },
    '雅各': { pinyin: 'Yǎgè', meaning: 'James', usage: 'Two apostles share this name: James son of Zebedee, and James son of Alphaeus (亚勒腓的儿子雅各).' },
    '约翰': { pinyin: 'Yuēhàn', meaning: 'John', usage: '雅各的兄弟约翰 = John, the brother of James.' },
    '半尼其': { pinyin: 'Bànníqí', meaning: 'Boanerges', usage: 'A nickname Jesus gave James and John. The next words explain it: 就是雷子的意思 = which means "sons of thunder".' },
    '雷子': { pinyin: 'léizǐ', meaning: 'sons of thunder', usage: '雷 (thunder) + 子 (sons). The meaning of the nickname 半尼其.' },
    '安得烈': { pinyin: 'Āndéliè', meaning: 'Andrew', usage: 'One of the twelve apostles, Simon Peter\'s brother.' },
    '腓力': { pinyin: 'Féilì', meaning: 'Philip', usage: 'One of the twelve apostles.' },
    '巴多罗买': { pinyin: 'Bāduōluómǎi', meaning: 'Bartholomew', usage: 'One of the twelve apostles.' },
    '马太': { pinyin: 'Mǎtài', meaning: 'Matthew', usage: 'One of the twelve apostles — a tax collector before following Jesus.' },
    '多马': { pinyin: 'Duōmǎ', meaning: 'Thomas', usage: 'One of the twelve apostles.' },
    '亚勒腓': { pinyin: 'Yàlèféi', meaning: 'Alphaeus', usage: 'The father of the second James: 亚勒腓的儿子雅各.' },
    '达太': { pinyin: 'Dátài', meaning: 'Thaddaeus', usage: 'One of the twelve apostles.' },
    '奋锐党': { pinyin: 'Fènruìdǎng', meaning: 'the Zealots', usage: '奋锐 (zealous, fiery) + 党 (party). 奋锐党的西门 = Simon from the Zealot party.' },
    '加略人': { pinyin: 'Jiālüèrén', meaning: 'man of Kerioth (Iscariot)', usage: '加略 is a place name + 人 (person from there). 加略人犹大 = Judas Iscariot.' },
    '犹大': { pinyin: 'Yóudà', meaning: 'Judas', usage: '卖耶稣的加略人犹大 = Judas Iscariot, who betrayed (sold) Jesus.' },

    // ---- verbs, nouns, adjectives ----
    '进': { pinyin: 'jìn', meaning: 'to enter, go in', usage: '进了会堂 = went into the synagogue. 进 + 了 shows the action is completed.' },
    '枯干': { pinyin: 'kūgān', meaning: 'withered, dried up', usage: '枯 (withered) + 干 (dry). 枯干了一只手 = one of his hands had withered.' },
    '手': { pinyin: 'shǒu', meaning: 'hand', usage: 'The story is about a man\'s withered hand: 一只手 = one hand.' },
    '人': { pinyin: 'rén', meaning: 'person, people', usage: '有一个人 = there was a person. Also in group names like 法利赛人 (Pharisee-people).' },
    '众人': { pinyin: 'zhòngrén', meaning: 'the crowd, everyone', usage: '众 (many) + 人 (people). 众人窥探耶稣 = the people all watched Jesus closely.' },
    '窥探': { pinyin: 'kuītàn', meaning: 'to spy on, watch secretly', usage: 'They watched Jesus secretly, hoping to catch him doing something wrong.' },
    '医治': { pinyin: 'yīzhì', meaning: 'to heal, cure', usage: '医治不医治 = "will he heal or not heal?" Repeating a verb with 不 in the middle makes a yes/no question.' },
    '意思': { pinyin: 'yìsi', meaning: 'meaning; intention', usage: 'v.2 意思是要控告耶稣 = their intention was to accuse Jesus. v.13 随自己的意思 = according to his own wish. v.17 雷子的意思 = the meaning "sons of thunder".' },
    '控告': { pinyin: 'kònggào', meaning: 'to accuse (in court)', usage: '要控告耶稣 = they wanted to accuse Jesus of breaking the Sabbath law.' },
    '说': { pinyin: 'shuō', meaning: 'to say, speak', usage: '对那人说 = said to that man. 说 usually comes right before the words someone speaks.' },
    '起来': { pinyin: 'qǐlái', meaning: 'get up, stand up', usage: 'Jesus\' command to the man: 起来 = Get up!' },
    '站': { pinyin: 'zhàn', meaning: 'to stand', usage: '站在当中 = stand in the middle (where everyone can see).' },
    '当中': { pinyin: 'dāngzhōng', meaning: 'the middle, the center', usage: '站在当中 = stand in the middle of everyone.' },
    '问': { pinyin: 'wèn', meaning: 'to ask', usage: '又问众人说 = then he asked the crowd.' },
    '行善': { pinyin: 'xíngshàn', meaning: 'to do good', usage: '行 (to do) + 善 (good). Jesus asks: on the Sabbath, 行善 or 行恶 — which is allowed?' },
    '行恶': { pinyin: 'xíng\'è', meaning: 'to do evil', usage: '行 (to do) + 恶 (evil). The opposite of 行善.' },
    '救命': { pinyin: 'jiùmìng', meaning: 'to save a life', usage: '救 (save) + 命 (life). Paired with its opposite 害命 in Jesus\' question.' },
    '害命': { pinyin: 'hàimìng', meaning: 'to destroy a life', usage: '害 (harm) + 命 (life). The opposite of 救命.' },
    '作声': { pinyin: 'zuòshēng', meaning: 'to make a sound', usage: '他们都不作声 = they all kept silent — nobody dared to answer.' },
    '怒目': { pinyin: 'nùmù', meaning: 'with angry eyes', usage: '怒 (anger) + 目 (eyes). 怒目周围看他们 = looked around at them with anger.' },
    '周围': { pinyin: 'zhōuwéi', meaning: 'around, on every side', usage: '周围看 = looked all around.' },
    '看': { pinyin: 'kàn', meaning: 'to look at', usage: '怒目周围看他们 = looked around at them (with angry eyes).' },
    '忧愁': { pinyin: 'yōuchóu', meaning: 'grieved, sad', usage: 'Jesus was both angry and sad: 忧愁他们的心刚硬 = grieved that their hearts were hard.' },
    '心': { pinyin: 'xīn', meaning: 'heart', usage: '他们的心刚硬 = their hearts were hard (stubborn, without pity).' },
    '刚硬': { pinyin: 'gāngyìng', meaning: 'hard, stubborn', usage: '心刚硬 = hard-hearted — they cared more about rules than about the sick man.' },
    '伸出': { pinyin: 'shēnchū', meaning: 'to stretch out', usage: '伸 (stretch) + 出 (out). Jesus\' command: 伸出手来 = Stretch out your hand!' },
    '伸': { pinyin: 'shēn', meaning: 'to stretch', usage: '把手一伸 = with one stretch of his hand. 一 + verb means "in one motion, as soon as".' },
    '复了原': { pinyin: 'fù le yuán', meaning: 'was restored, became like before', usage: 'This is 复原 (recover) with 了 in the middle. 手就复了原 = the hand was made completely well again.' },
    '出去': { pinyin: 'chūqù', meaning: 'to go out', usage: '法利赛人出去 = the Pharisees went out (of the synagogue).' },
    '一党': { pinyin: 'yìdǎng', meaning: 'one party, one group', usage: '希律一党的人 = the people of Herod\'s party — usually enemies of the Pharisees, but here they team up.' },
    '商议': { pinyin: 'shāngyì', meaning: 'to discuss and plan together', usage: '商议怎样可以除灭耶稣 = plotted how they could destroy Jesus.' },
    '怎样': { pinyin: 'zěnyàng', meaning: 'how', usage: '怎样可以除灭 = how they could destroy (him).' },
    '除灭': { pinyin: 'chúmiè', meaning: 'to destroy, get rid of', usage: '除 (remove) + 灭 (wipe out). A very strong word — they wanted to kill Jesus.' },
    '门徒': { pinyin: 'méntú', meaning: 'disciple(s)', usage: 'Students who follow a teacher everywhere. 耶稣和门徒 = Jesus and his disciples.' },
    '退到': { pinyin: 'tuìdào', meaning: 'to withdraw to', usage: '退 (step back) + 到 (arrive at). 退到海边去 = withdrew to the seaside.' },
    '海边': { pinyin: 'hǎibiān', meaning: 'the seaside', usage: '海 (sea) + 边 (side/edge) — the shore of the Sea of Galilee.' },
    '许多': { pinyin: 'xǔduō', meaning: 'many, a lot of', usage: '许多人 = many people. 治好了许多人 = healed many people.' },
    '跟随': { pinyin: 'gēnsuí', meaning: 'to follow', usage: '跟随他 = followed him (wherever he went).' },
    '听见': { pinyin: 'tīngjiàn', meaning: 'to hear', usage: '听 (listen) + 见 (perceive): the sound reached their ears. 听见他所做的大事 = heard about the great things he did.' },
    '做': { pinyin: 'zuò', meaning: 'to do', usage: '他所做的大事 = the great things that he did.' },
    '大事': { pinyin: 'dàshì', meaning: 'great things, mighty deeds', usage: '大 (great) + 事 (things) — the miracles Jesus did.' },
    '外': { pinyin: 'wài', meaning: 'outside, beyond', usage: '约旦河外 = (the land) beyond the Jordan River.' },
    '四方': { pinyin: 'sìfāng', meaning: 'the region all around', usage: '四 (four) + 方 (directions). 泰尔、西顿的四方 = the whole region around Tyre and Sidon.' },
    '来到': { pinyin: 'láidào', meaning: 'to come to', usage: '来到他那里 = came to (the place where) he (was).' },
    '吩咐': { pinyin: 'fēnfù', meaning: 'to instruct, tell (someone to do something)', usage: '吩咐门徒 = told the disciples (to get a boat ready).' },
    '小船': { pinyin: 'xiǎochuán', meaning: 'small boat', usage: '小 (small) + 船 (boat). 叫一只小船伺候着 = have a small boat kept ready.' },
    '伺候': { pinyin: 'cìhòu', meaning: 'to wait on, stand ready', usage: '伺候着 = staying ready to serve — the boat waited nearby in case the crowd pressed too hard.' },
    '免得': { pinyin: 'miǎndé', meaning: 'so that ... not; to avoid', usage: '免得众人拥挤他 = so that the crowd would not crush him.' },
    '拥挤': { pinyin: 'yōngjǐ', meaning: 'to crowd, press against', usage: 'So many people pushed toward Jesus that they might crush him.' },
    '治好': { pinyin: 'zhìhǎo', meaning: 'to heal completely', usage: '治 (treat) + 好 (well). 治好了许多人 = had healed many people.' },
    '灾病': { pinyin: 'zāibìng', meaning: 'diseases, afflictions', usage: '灾 (disaster) + 病 (sickness). 凡有灾病的 = all who had diseases.' },
    '挤进来': { pinyin: 'jǐ jìnlái', meaning: 'to push one\'s way in', usage: '挤 (squeeze) + 进来 (come in). The sick pushed through the crowd to reach Jesus.' },
    '摸': { pinyin: 'mō', meaning: 'to touch', usage: '要摸他 = wanted to touch him — they believed touching Jesus would heal them.' },
    '看见': { pinyin: 'kànjiàn', meaning: 'to see', usage: '看 (look) + 见 (perceive). 无论何时看见他 = whenever they saw him.' },
    '俯伏': { pinyin: 'fǔfú', meaning: 'to fall down, bow to the ground', usage: '俯伏在他面前 = fell down before him.' },
    '面前': { pinyin: 'miànqián', meaning: 'in front of, before', usage: '在他面前 = before him, in front of him.' },
    '喊': { pinyin: 'hǎn', meaning: 'to shout, cry out', usage: '喊着说 = cried out, saying. The 着 shows the shouting keeps going while they speak.' },
    '儿子': { pinyin: 'érzi', meaning: 'son', usage: '神的儿子 = the Son of God. Also 西庇太的儿子 = the son of Zebedee.' },
    '再三': { pinyin: 'zàisān', meaning: 'again and again', usage: '再 (again) + 三 (three) — literally "again and a third time". 再三的嘱咐 = warned them repeatedly.' },
    '嘱咐': { pinyin: 'zhǔfù', meaning: 'to charge, warn earnestly', usage: 'To tell someone firmly and seriously. 耶稣再三的嘱咐他们 = Jesus strictly ordered them.' },
    '显露': { pinyin: 'xiǎnlù', meaning: 'to reveal, make known', usage: '不要把他显露出来 = do not make him known (do not tell everyone who he is).' },
    '出来': { pinyin: 'chūlái', meaning: 'out (into the open)', usage: 'After a verb, 出来 means the action brings something into the open: 显露出来 = reveal openly.' },
    '上': { pinyin: 'shàng', meaning: 'to go up', usage: '上了山 = went up the mountain.' },
    '山': { pinyin: 'shān', meaning: 'mountain, hill', usage: '耶稣上了山 = Jesus went up the mountain.' },
    '随': { pinyin: 'suí', meaning: 'according to, following', usage: '随自己的意思 = according to his own wish — Jesus himself chose whom to call.' },
    '自己': { pinyin: 'zìjǐ', meaning: 'oneself, one\'s own', usage: '自己的意思 = his own wish. 和自己同在 = to be with him (Jesus himself).' },
    '设立': { pinyin: 'shèlì', meaning: 'to appoint, establish', usage: '设立十二个人 = appointed twelve people (the twelve apostles).' },
    '十二': { pinyin: 'shí\'èr', meaning: 'twelve', usage: '十 (ten) + 二 (two) = 12. 十二个人 = twelve people.' },
    '同在': { pinyin: 'tóngzài', meaning: 'to be together with', usage: '常和自己同在 = to be with him always — the first job of the twelve.' },
    '差': { pinyin: 'chāi', meaning: 'to send (someone on a mission)', usage: '差他们去传道 = send them out to preach. (In this meaning 差 is read chāi, not chà.)' },
    '传道': { pinyin: 'chuándào', meaning: 'to preach', usage: '传 (spread) + 道 (the Way, the message) = spread God\'s message.' },
    '权柄': { pinyin: 'quánbǐng', meaning: 'authority, power', usage: '权 (power) + 柄 (handle). 给他们权柄赶鬼 = gave them authority to cast out demons.' },
    '赶鬼': { pinyin: 'gǎnguǐ', meaning: 'to cast out demons', usage: '赶 (drive away) + 鬼 (demons).' },
    '起名': { pinyin: 'qǐmíng', meaning: 'to give a name', usage: '起名叫彼得 = gave him the name Peter. 给…起名叫… = named (someone) (a name).' },
    '兄弟': { pinyin: 'xiōngdì', meaning: 'brother', usage: '雅各的兄弟约翰 = John, the brother of James.' },
    '卖': { pinyin: 'mài', meaning: 'to sell; here: to betray', usage: '卖耶稣的 = the one who betrayed (literally "sold") Jesus — for thirty pieces of silver.' },

    // ---- small grammar words ----
    '又': { pinyin: 'yòu', meaning: 'again; also', usage: '耶稣又进了会堂 = Jesus went into the synagogue again. Also joins actions: 又问众人 = and he asked the crowd.' },
    '了': { pinyin: 'le', meaning: '(particle: action completed)', usage: 'Placed after a verb to show the action is finished: 进了 = entered, 上了山 = went up the mountain, 治好了 = has healed.' },
    '在': { pinyin: 'zài', meaning: 'at, in, on', usage: '在那里 = there (at that place); 在安息日 = on the Sabbath; 站在当中 = stand in the middle.' },
    '那里': { pinyin: 'nàlǐ', meaning: 'there, that place', usage: '在那里 = in that place. 来到他那里 = came to where he was.' },
    '有': { pinyin: 'yǒu', meaning: 'to have; there is/are', usage: '有一个人 = there was a person. 凡有灾病的 = all who had diseases. 这十二个人有西门 = among the twelve was Simon.' },
    '一个': { pinyin: 'yí gè', meaning: 'one, a (person/thing)', usage: 'Number 一 + measure word 个. 一个人 = one person.' },
    '一只': { pinyin: 'yì zhī', meaning: 'one (measure word 只)', usage: '只 is the measure word for hands, boats and animals: 一只手 = one hand; 一只小船 = a small boat.' },
    '不': { pinyin: 'bù', meaning: 'not, no', usage: '医治不医治 = heal or not heal? 不作声 = made no sound.' },
    '是': { pinyin: 'shì', meaning: 'to be (is, am, are)', usage: '你是神的儿子 = You are the Son of God. 意思是… = the meaning is…' },
    '要': { pinyin: 'yào', meaning: 'to want to; to be about to', usage: '要控告耶稣 = wanted to accuse Jesus. 要他们常和自己同在 = wanted them to be with him.' },
    '对': { pinyin: 'duì', meaning: 'to, toward (someone)', usage: 'Marks who is spoken to: 对那人说 = said to that man.' },
    '那': { pinyin: 'nà', meaning: 'that', usage: '那人 = that man; 那枯干一只手的人 = that man with the withered hand.' },
    '的': { pinyin: 'de', meaning: '(connecting particle: \'s / who...)', usage: 'Connects a description to a noun: 神的儿子 = God\'s son; 枯干一只手的人 = the man whose hand was withered.' },
    '地': { pinyin: 'de', meaning: '(particle: turns a word into HOW something is done)', usage: 'Comes before a verb: 再三地嘱咐 = warned them again and again, earnestly.' },
    '哪样': { pinyin: 'nǎyàng', meaning: 'which one (of the two)?', usage: '哪 = which. 哪样是可以的呢？ = which one is allowed (to do good, or to do evil)?' },
    '可以': { pinyin: 'kěyǐ', meaning: 'allowed, permitted; can', usage: '是可以的 = is allowed. 怎样可以除灭耶稣 = how they could destroy Jesus.' },
    '呢': { pinyin: 'ne', meaning: '(question particle)', usage: 'Placed at the end to soften a question: 哪样是可以的呢？ = so which one is allowed?' },
    '他们': { pinyin: 'tāmen', meaning: 'they, them', usage: '他 (he) + 们 (plural marker). 他们都不作声 = they all said nothing.' },
    '都': { pinyin: 'dōu', meaning: 'all', usage: '他们都不作声 = they ALL kept silent; 都挤进来 = all pushed in.' },
    '就': { pinyin: 'jiù', meaning: 'then, so, right away', usage: 'Links to what happens next: 手就复了原 = and the hand was restored at once.' },
    '来': { pinyin: 'lái', meaning: 'to come', usage: '叫人来 = called people to come. After a verb it points toward the speaker: 伸出手来 = stretch out (your) hand (toward me).' },
    '他': { pinyin: 'tā', meaning: 'he, him', usage: '他把手一伸 = he stretched out his hand; 跟随他 = followed him.' },
    '把': { pinyin: 'bǎ', meaning: '(particle: moves the object before the verb)', usage: '把手一伸 = took his hand and stretched it. 把他显露出来 = make him known.' },
    '一': { pinyin: 'yī', meaning: 'one; (with a verb) in one motion', usage: '手一伸 = with one stretch of the hand — 一 + verb means "as soon as, in one quick motion".' },
    '同': { pinyin: 'tóng', meaning: 'with, together with', usage: '同希律一党的人商议 = plotted together with Herod\'s party.' },
    '和': { pinyin: 'hé', meaning: 'and; with', usage: '耶稣和门徒 = Jesus and the disciples; 常和自己同在 = be together with him.' },
    '去': { pinyin: 'qù', meaning: 'to go', usage: 'After a place it shows moving away: 退到海边去 = went off to the seaside. 差他们去传道 = send them out to preach.' },
    '从': { pinyin: 'cóng', meaning: 'from', usage: '从加利利 = from Galilee; 从犹太 = from Judea.' },
    '还有': { pinyin: 'háiyǒu', meaning: 'and also, there were also', usage: '还有许多人 = and many more people also (came). 还有卖耶稣的犹大 = and also Judas who betrayed Jesus.' },
    '所': { pinyin: 'suǒ', meaning: '(grammar word: that which...)', usage: '他所做的大事 = the great things THAT he did. 所 + verb turns the action into "the things done".' },
    '并': { pinyin: 'bìng', meaning: 'and, and also', usage: 'Joins list items: 并泰尔、西顿 = and Tyre and Sidon; 并给他们权柄 = and gave them authority.' },
    '因为': { pinyin: 'yīnwèi', meaning: 'because', usage: '因为人多 = because there were so many people.' },
    '多': { pinyin: 'duō', meaning: 'many, much', usage: '人多 = the people were many (it was very crowded).' },
    '叫': { pinyin: 'jiào', meaning: 'to tell/ask (someone to do); to call, name', usage: 'v.9 叫一只小船伺候着 = have a boat kept ready; v.13 叫人来 = called people to come; v.16 起名叫彼得 = named him Peter.' },
    '着': { pinyin: 'zhe', meaning: '(particle: ongoing state)', usage: 'Shows an action keeps going: 伺候着 = staying ready; 喊着说 = kept shouting while saying.' },
    '所以': { pinyin: 'suǒyǐ', meaning: 'so, therefore', usage: '所以凡有灾病的都挤进来 = therefore all the sick pushed in.' },
    '凡': { pinyin: 'fán', meaning: 'all who, whoever', usage: '凡有灾病的 = all those who had diseases.' },
    '无论': { pinyin: 'wúlùn', meaning: 'no matter (what/when)', usage: '无论何时 = no matter when = whenever.' },
    '何时': { pinyin: 'héshí', meaning: 'what time, when', usage: 'A formal word for 什么时候. 无论何时看见他 = whenever they saw him.' },
    '你': { pinyin: 'nǐ', meaning: 'you', usage: '你是神的儿子 = YOU are the Son of God.' },
    '不要': { pinyin: 'búyào', meaning: 'do not', usage: '不要把他显露出来 = do not make him known.' },
    '便': { pinyin: 'biàn', meaning: 'then (literary word for 就)', usage: '他们便来到他那里 = and so they came to him.' },
    '个': { pinyin: 'gè', meaning: '(measure word for people/things)', usage: '十二个人 = twelve people; 两个人 = two people.' },
    '常': { pinyin: 'cháng', meaning: 'always, constantly', usage: '常和自己同在 = to be with him always.' },
    '也': { pinyin: 'yě', meaning: 'also', usage: '也要差他们去传道 = and also to send them out to preach.' },
    '给': { pinyin: 'gěi', meaning: 'to give', usage: '给他们权柄 = gave them authority; 给他起名 = gave him a name.' },
    '这': { pinyin: 'zhè', meaning: 'this, these', usage: '这十二个人 = these twelve people; 这两个人 = these two people.' },
    '两个': { pinyin: 'liǎng gè', meaning: 'two (people/things)', usage: 'Before a measure word, "two" is 两 not 二: 这两个人 = these two people (James and John).' },
    '就是': { pinyin: 'jiùshì', meaning: 'that is, which means', usage: '就是雷子的意思 = which means "sons of thunder" — explaining the name 半尼其.' },
  },
};
