// 马可福音 3:20–35 · 和合本（神版）
import mark3 from './mark-3.js?v=3';

export default {
  id: 'mark-3-20-35',
  tabTitle: 'Mark 3:20–35',
  title: '马可福音 3:20–35',
  subtitle: '和合本（神版） · Mark 3:20–35',

  paragraphs: [
    {
      id: 'p1',
      artCaption: '屋里屋外 · A crowded house (v.20–22)',
      artImage: 'assets/illustrations/mark-3-20-22.jpg',
      artAlt: '耶稣在拥挤的屋子里教导众人，亲属站在门外。',
      artPrompt:
        'Child-friendly clay-animation illustration, no text: a crowded first-century home where Jesus teaches, ' +
        'with concerned family members waiting outside the open door.',
      verses: [
        { n: 20, tokens: ['耶稣', '进', '了', '一个', '屋子', '，', '众人', '又', '聚集', '，', '甚至', '他', '连', '饭', '也', '顾不得', '吃', '。'] },
        { n: 21, tokens: ['耶稣', '的', '亲属', '听见', '，', '就', '出来', '要', '拉住', '他', '，', '因为', '他们', '说', '他', '癫狂', '了', '。'] },
        { n: 22, tokens: ['从', '耶路撒冷', '下来', '的', '文士', '说', '：', '「', '他', '是', '被', '别西卜', '附着', '」', '；', '又', '说', '：', '「', '他', '是', '靠着', '鬼王', '赶鬼', '。', '」'] },
      ],
    },
    {
      id: 'p2',
      artCaption: '一国与一家 · A house divided (v.23–30)',
      artImage: 'assets/illustrations/mark-3-23-30.jpg',
      artAlt: '耶稣坐在院子里教导众人，地上画着分开的房子和被捆住的壮士。',
      artPrompt:
        'Bright child-friendly comic-book illustration, no text: Jesus explains a divided house using simple ' +
        'drawings in the sand, with a peaceful listening crowd in an ancient courtyard.',
      verses: [
        { n: 23, tokens: ['耶稣', '叫', '他们', '来', '，', '用', '比喻', '对', '他们', '说', '：', '「', '撒但', '怎能', '赶出', '撒但', '呢', '？'] },
        { n: 24, tokens: ['若', '一国', '自相', '纷争', '，', '那国', '就', '站立不住', '；'] },
        { n: 25, tokens: ['若', '一家', '自相', '纷争', '，', '那家', '就', '站立不住', '。'] },
        { n: 26, tokens: ['若', '撒但', '自相', '攻打', '纷争', '，', '他', '就', '站立不住', '，', '必要', '灭亡', '。'] },
        { n: 27, tokens: ['没有人', '能', '进', '壮士', '家里', '，', '抢夺', '他', '的', '家具', '；', '必先', '捆住', '那', '壮士', '，', '才', '可以', '抢夺', '他', '的', '家', '。'] },
        { n: 28, tokens: ['我', '实在', '告诉', '你们', '，', '世人', '一切', '的', '罪', '和', '一切', '亵渎', '的', '话', '都', '可得', '赦免', '；'] },
        { n: 29, tokens: ['凡', '亵渎', '圣灵', '的', '，', '却', '永不得', '赦免', '，', '乃', '要', '担当', '永远', '的', '罪', '。', '」'] },
        { n: 30, tokens: ['这话', '是', '因为', '他们', '说', '：', '「', '他', '是', '被', '污鬼', '附着', '的', '。', '」'] },
      ],
    },
    {
      id: 'p3',
      artCaption: '谁是我的家人？ · God’s family (v.31–35)',
      artImage: 'assets/illustrations/mark-3-31-35.jpg',
      artAlt: '耶稣在屋子里环顾坐着的人，母亲和弟兄站在外边。',
      artPrompt:
        'Tender colored-pencil children’s-book illustration, no text: Jesus warmly looks at people seated with ' +
        'him inside a house while his mother and brothers wait respectfully outside.',
      verses: [
        { n: 31, tokens: ['当下', '，', '耶稣', '的', '母亲', '和', '弟兄', '来', '，', '站', '在', '外边', '，', '打发', '人', '去', '叫', '他', '。'] },
        { n: 32, tokens: ['有', '许多', '人', '在', '耶稣', '周围', '坐着', '，', '他们', '就', '告诉', '他', '说', '：', '「', '看哪', '，', '你', '母亲', '和', '你', '弟兄', '在', '外边', '找', '你', '。', '」'] },
        { n: 33, tokens: ['耶稣', '回答', '说', '：', '「', '谁', '是', '我的', '母亲', '？', '谁', '是', '我的', '弟兄', '？', '」'] },
        { n: 34, tokens: ['就', '四面', '观看', '那', '周围', '坐着', '的', '人', '，', '说', '：', '「', '看哪', '，', '我的', '母亲', '，', '我的', '弟兄', '。'] },
        { n: 35, tokens: ['凡', '遵行', '神旨意', '的', '人', '就是', '我的', '弟兄姊妹', '和', '母亲', '了', '。', '」'] },
      ],
    },
  ],

  // Reuse the first lesson’s explanations, then add the vocabulary unique to v.20–35.
  dict: {
    ...mark3.dict,
    '屋子': { pinyin: 'wūzi', meaning: 'house; room', usage: '耶稣进了一个屋子 = Jesus went into a house.' },
    '聚集': { pinyin: 'jùjí', meaning: 'to gather together', usage: '众人又聚集 = the crowd gathered together again.' },
    '甚至': { pinyin: 'shènzhì', meaning: 'even; so much that', usage: 'It makes the next detail stronger: the crowd was so large that Jesus could not even eat.' },
    '连': { pinyin: 'lián', meaning: 'even', usage: '连饭也顾不得吃 = he could not even take time to eat.' },
    '饭': { pinyin: 'fàn', meaning: 'meal; food', usage: '吃饭 = eat a meal. Here 饭 is the food Jesus did not have time to eat.' },
    '顾不得': { pinyin: 'gùbudé', meaning: 'to have no time for; cannot attend to', usage: '顾 (look after) + 不得 (cannot). 顾不得吃 = could not spare time to eat.' },
    '吃': { pinyin: 'chī', meaning: 'to eat', usage: '吃饭 = eat a meal.' },
    '亲属': { pinyin: 'qīnshǔ', meaning: 'relatives; family members', usage: '亲 (close) + 属 (belonging). 耶稣的亲属 = Jesus’ relatives.' },
    '拉住': { pinyin: 'lāzhù', meaning: 'to pull and hold onto', usage: '拉 (pull) + 住 (hold firmly). They came to bring Jesus away.' },
    '癫狂': { pinyin: 'diānkuáng', meaning: 'out of one’s mind; crazy', usage: 'This is what the relatives said about Jesus; it is their mistaken opinion, not what the lesson teaches.' },
    '下来': { pinyin: 'xiàlái', meaning: 'to come down', usage: '从耶路撒冷下来 = came down from Jerusalem.' },
    '文士': { pinyin: 'wénshì', meaning: 'scribe; religious law teacher', usage: '文 (writing) + 士 (learned person). 文士 studied and taught religious laws.' },
    '被': { pinyin: 'bèi', meaning: '(passive marker: by)', usage: '被别西卜附着 = said to be possessed by Beelzebul. 被 marks something happening to someone.' },
    '别西卜': { pinyin: 'Biéxībǔ', meaning: 'Beelzebul', usage: 'A name the scribes used for the ruler of demons.' },
    '附着': { pinyin: 'fùzhuó', meaning: 'to attach to; cling to', usage: '附 (attach) + 着 (remain attached). The scribes wrongly claimed an unclean spirit was attached to Jesus.' },
    '靠着': { pinyin: 'kàozhe', meaning: 'by relying on; through', usage: '靠着鬼王赶鬼 = by the power of the ruler of demons, as the scribes falsely claimed.' },
    '鬼王': { pinyin: 'guǐwáng', meaning: 'ruler of demons', usage: '鬼 (demon) + 王 (king). This is the accusation the scribes made.' },
    '用': { pinyin: 'yòng', meaning: 'to use; with', usage: '用比喻 = by using a parable.' },
    '比喻': { pinyin: 'bǐyù', meaning: 'parable; comparison story', usage: 'Jesus uses an everyday picture, such as a house, to teach an important idea.' },
    '撒但': { pinyin: 'Sādàn', meaning: 'Satan', usage: 'The Chinese Bible name for Satan. Jesus asks whether Satan could drive out Satan.' },
    '怎能': { pinyin: 'zěnnéng', meaning: 'how can?', usage: '怎 (how) + 能 (can). 撒但怎能赶出撒但呢？ = How can Satan drive out Satan?' },
    '赶出': { pinyin: 'gǎnchū', meaning: 'to drive out', usage: '赶 (drive away) + 出 (out). 赶出撒但 = drive Satan out.' },
    '若': { pinyin: 'ruò', meaning: 'if', usage: 'A formal Bible word for 如果. 若一国… = if a kingdom…' },
    '一国': { pinyin: 'yí guó', meaning: 'one kingdom; a country', usage: '一 (one) + 国 (country). Jesus begins with the picture of a country divided against itself.' },
    '自相': { pinyin: 'zìxiāng', meaning: 'each other; among themselves', usage: '自相纷争 = fight one another.' },
    '纷争': { pinyin: 'fēnzhēng', meaning: 'to quarrel and fight', usage: '纷 (many tangled things) + 争 (fight). 自相纷争 = fighting each other.' },
    '那国': { pinyin: 'nà guó', meaning: 'that country', usage: '那 (that) + 国 (country). 那国就站立不住 = that country cannot stand.' },
    '站立不住': { pinyin: 'zhànlì bù zhù', meaning: 'cannot stand; cannot last', usage: 'Here it is a picture: a divided kingdom or family cannot keep going.' },
    '一家': { pinyin: 'yì jiā', meaning: 'one household; a family', usage: '一家自相纷争 = one family fighting among itself.' },
    '那家': { pinyin: 'nà jiā', meaning: 'that household', usage: '那家就站立不住 = that family cannot stay together.' },
    '攻打': { pinyin: 'gōngdǎ', meaning: 'to attack', usage: '撒但自相攻打 = Satan attacking himself.' },
    '必要': { pinyin: 'bìyào', meaning: 'certainly will; must', usage: '必 (certainly) + 要 (will). 必要灭亡 = will surely fall apart.' },
    '灭亡': { pinyin: 'mièwáng', meaning: 'to perish; come to an end', usage: '灭 (destroy) + 亡 (be gone). Here it means completely coming to an end.' },
    '没有人': { pinyin: 'méiyǒu rén', meaning: 'no one', usage: '没有人能… = no one can…' },
    '能': { pinyin: 'néng', meaning: 'can; be able to', usage: '没有人能进… = no one is able to enter…' },
    '壮士': { pinyin: 'zhuàngshì', meaning: 'strong man', usage: '壮 (strong) + 士 (man). Jesus uses a strong man as part of a comparison story.' },
    '家': { pinyin: 'jiā', meaning: 'home; household', usage: '壮士的家 = the strong man’s home. 家 can mean a building or the people who live together.' },
    '家里': { pinyin: 'jiālǐ', meaning: 'inside a home', usage: '家 (home) + 里 (inside). 进壮士家里 = enter the strong man’s house.' },
    '抢夺': { pinyin: 'qiǎngduó', meaning: 'to take by force; seize', usage: '抢 (snatch) + 夺 (take away). It is part of Jesus’ comparison, not an instruction.' },
    '家具': { pinyin: 'jiājù', meaning: 'household goods; belongings', usage: '家 (home) + 具 (things). 家具 means the things in a person’s house.' },
    '必先': { pinyin: 'bìxiān', meaning: 'must first', usage: '必 (must) + 先 (first). 必先捆住… = must first tie up…' },
    '捆住': { pinyin: 'kǔnzhù', meaning: 'to tie up; bind', usage: '捆 (tie) + 住 (fasten firmly). It is part of the strong-man comparison.' },
    '才': { pinyin: 'cái', meaning: 'only then', usage: '必先…才可以… = only after doing the first thing can the next thing happen.' },
    '我': { pinyin: 'wǒ', meaning: 'I; me', usage: '我实在告诉你们 = I truly tell you.' },
    '实在': { pinyin: 'shízài', meaning: 'truly; really', usage: 'Jesus uses 实在 to show that his next words are very important.' },
    '告诉': { pinyin: 'gàosu', meaning: 'to tell', usage: '告诉你们 = tell you all.' },
    '你们': { pinyin: 'nǐmen', meaning: 'you (plural)', usage: '你 (you) + 们 (plural). Jesus is speaking to more than one listener.' },
    '世人': { pinyin: 'shìrén', meaning: 'people of the world; humankind', usage: '世 (world) + 人 (people). 世人 means all people.' },
    '一切': { pinyin: 'yíqiè', meaning: 'all; every kind of', usage: '一切的罪 = every kind of sin.' },
    '罪': { pinyin: 'zuì', meaning: 'sin; wrongdoing', usage: '罪 means actions and attitudes that go against God’s good way.' },
    '亵渎': { pinyin: 'xièdú', meaning: 'to speak disrespectfully about what is holy', usage: 'A serious word for treating God or holy things with contempt.' },
    '话': { pinyin: 'huà', meaning: 'words; speech', usage: '亵渎的话 = disrespectful words.' },
    '可得': { pinyin: 'kědé', meaning: 'can receive; may be given', usage: '可 (can) + 得 (receive). 可得赦免 = can receive forgiveness.' },
    '赦免': { pinyin: 'shèmiǎn', meaning: 'to forgive; pardon', usage: '赦 (pardon) + 免 (release). 赦免 means being forgiven.' },
    '圣灵': { pinyin: 'Shènglíng', meaning: 'the Holy Spirit', usage: '圣 (holy) + 灵 (spirit). The Holy Spirit is God’s Holy Spirit.' },
    '却': { pinyin: 'què', meaning: 'but; however', usage: '却 shows a strong contrast with what was said before.' },
    '永不得': { pinyin: 'yǒng bù dé', meaning: 'never receive; never obtain', usage: '永 (forever) + 不得 (not receive). This is a very serious warning in the passage.' },
    '乃': { pinyin: 'nǎi', meaning: 'instead; rather', usage: 'A formal Bible word that introduces what is true instead.' },
    '担当': { pinyin: 'dāndāng', meaning: 'to bear; take responsibility for', usage: '担 (carry) + 当 (take on). 担当永远的罪 = bear the responsibility for an eternal sin.' },
    '永远': { pinyin: 'yǒngyuǎn', meaning: 'forever; eternal', usage: '永 (forever) + 远 (far). 永远的罪 = an eternal sin.' },
    '这话': { pinyin: 'zhè huà', meaning: 'these words; this saying', usage: '这话是因为… = Jesus said this because…' },
    '当下': { pinyin: 'dāngxià', meaning: 'right then; at that moment', usage: 'A Bible-style phrase for immediately at that time.' },
    '母亲': { pinyin: 'mǔqin', meaning: 'mother', usage: '耶稣的母亲 = Jesus’ mother.' },
    '弟兄': { pinyin: 'dìxiong', meaning: 'brother(s)', usage: '弟 (younger brother) + 兄 (older brother). Here it means Jesus’ brothers.' },
    '外边': { pinyin: 'wàibian', meaning: 'outside', usage: '外 (outside) + 边 (side). 站在外边 = stand outside.' },
    '打发': { pinyin: 'dǎfa', meaning: 'to send someone', usage: '打发人去叫他 = sent someone to call him.' },
    '坐着': { pinyin: 'zuòzhe', meaning: 'sitting; seated', usage: '坐 (sit) + 着 (ongoing state). 周围坐着的人 = the people sitting around him.' },
    '看哪': { pinyin: 'kàn nǎ', meaning: 'look! see!', usage: 'A Bible phrase that calls attention to something important.' },
    '找': { pinyin: 'zhǎo', meaning: 'to look for; seek', usage: '在外边找你 = outside looking for you.' },
    '回答': { pinyin: 'huídá', meaning: 'to answer', usage: '回 (reply) + 答 (answer). 耶稣回答说 = Jesus answered.' },
    '谁': { pinyin: 'shéi', meaning: 'who', usage: '谁是我的母亲？ = Who is my mother?' },
    '我的': { pinyin: 'wǒ de', meaning: 'my; mine', usage: '我 (I) + 的 (possessive marker). 我的母亲 = my mother.' },
    '四面': { pinyin: 'sìmiàn', meaning: 'all around; on every side', usage: '四 (four) + 面 (sides). 四面观看 = looked all around.' },
    '观看': { pinyin: 'guānkàn', meaning: 'to look at; watch', usage: '观 and 看 both mean look. 观看 is a more careful, formal kind of looking.' },
    '遵行': { pinyin: 'zūnxíng', meaning: 'to obey and do', usage: '遵 (follow) + 行 (carry out). 遵行神旨意 = obey and do God’s will.' },
    '神旨意': { pinyin: 'Shén zhǐyì', meaning: 'God’s will', usage: '神 (God) + 旨意 (purpose, will). It means what God wants people to do.' },
    '弟兄姊妹': { pinyin: 'dìxiōng zǐmèi', meaning: 'brothers and sisters', usage: '弟兄 (brothers) + 姊妹 (sisters). Jesus calls everyone who obeys God’s will part of his family.' },
  },
};
